{% set version = "0.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-leafem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/leafem_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/leafem/leafem_{{ version }}.tar.gz
  sha256: 81190dfb22139c8764b3bd71a13b746defabb03dddc85eb50cade1673deb88f8

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-leaflet >=2.0.1
    - r-mapdeck
    - r-raster
    - r-sf
    - r-sp
    - r-base64enc
    - r-scales >=1.0.0
    - r-png
  run:
    - r-base
    - r-htmltools >=0.3
    - r-htmlwidgets
    - r-leaflet >=2.0.1
    - r-mapdeck
    - r-raster
    - r-sf
    - r-sp
    - r-base64enc
    - r-scales >=1.0.0
    - r-png

test:
  commands:
    - R -e "library('leafem')"

about:
  home: https://github.com/r-spatial/leafem
  license: MIT
  summary: Provides extensions for packages 'leaflet' & 'mapdeck', many of which are used by
    package 'mapview'. Focus is on functionality readily available in Geographic Information
    Systems such as 'Quantum GIS'. Includes functions to display coordinates of mouse
    pointer position, query image values via mouse pointer and zoom-to-layer buttons.
    Additionally, provides a feature type agnostic function to add points, lines, polygons
    to a map.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r
