appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: A2NIxl6j1eOpbQc192RDfYCGQIHe01tAIwKFY3B6drgtdJMifLhUhbTOMiG2nld4FEOykNXTfLCigr2V0q0eX+UDgZfx9ZMIzqCa1XAymtF+kBqMr3Ia4quS+vmMB1LoeQA+Ni0uAprhVaAmEcrRS352RKkR72INPmWrmeIrQihN1TQUse4yh36Vlh8+JSlywizrJDkl1iAbNTUT7Jn37XfiL3gpwW3HqXDnjAxthvQtfy1H+4qW1+WqhpIxMU88JJS2I+cnl3Y0h+XDjrRHcp0RbHw6Gom8QlH0r9xXA3CN7H1As/S97mx5g16/K3BsjaOXMgBHcAfWKzOYl6o09DNxmLpnfDRJXRkVM8eoVW0iT96lMA5ZtC97i/+7Gfr0n8ku8JKExFTQWlt3Z2lcl/ak06Ko/FrcyMg4KTuD8ZczLB2nLTFXBNx4ZpJHJ0AycFpy082T/VD7INdegr1N8f4q2huqhdUrgYF0GaJnFhEC4uRGzZzZ0jWSw0UIXdw+Ezi/36kLDwrzisLRWZRs9lYShOCtP4kahptWyYfyI6CSkNxglvNPN5rYlTP/TbaGYJq0y2U3fsbAvKqpo/L20nw8W4Sm/P5wqLOBstGd8Fs6ACaQ6C64TW26ztuPTcGlMtIWejDqJtwEnx2Eom3r421WIELelNwD7L4twsc/ZPM=}
bot:
  automerge: true
